# ----
# Site

title: Dokumentado
url: https://lakto.github.io/dokumentado
version: v1.0.0
baseurl:
google_analytics_key:
show_full_navigation: true
template: https://code.getmdl.io/1.3.0/material.blue_grey-amber.min.css
git:
  name: Github
  repository: Dokumentado
  url: https://github.com/lakto/dokumentado

company:
  company_name: Lakto.design
  mission_statement: Rezykliertes, Digitales und mehr
  address: Solothurn
  phone:
  email: info@lakto.org
  twitter:
  github: lakto


links:
  company: <a href="https://lakto.design">lakto.design</a>
  knora: <a href="https://knora.org">Knora</a>
  knora-docs: <a href="https://docs.knora.org">Documentation</a>
  knora-ui: <a href="https://npmjs.com/~knora">Knora-ui modules</a>
  sipi: <a href="https://sipi.io">Sipi</a>
  salsah: <a href="https://dhlab-basel.github.io/Salsah">Salsah</a>
  dhlab: <a href="http://dhlab.unibas.ch">Digital Humanities Lab</a>
  dasch: <a href="http://dasch.swiss">Data and Service Center for the Humanities</a>
  unibas: <a href="http://unibas.ch">University of Basel</a>


# Values for the jekyll-seo-tag gem (https://github.com/jekyll/jekyll-seo-tag)
logo: assets/images/touch-icon.png
description: Documentation and landing page template for Jekyll, useful for GitHub pages.
author:
  name: André Kilchenmann
  email: info@lakto.org

# -----
# Build

timezone: Etc/UTC

permalink: pretty

collections:
  docs:
    output: true
    permalink: docs/:path/
  manual:
    output: true
    permalink: manual/:path/
  features:
    output: true
    permalink: features/:name

defaults:
-
  scope:
    path: ""
  values:
    layout: "default"
-
  scope:
    path: ""
    type: "docs"
  values:
    layout: post
    seo:
      type: Article
-
  scope:
    path: ""
    type: "manual"
  values:
    layout: post
    seo:
      type: Article
-
  scope:
    path: ""
    type: "releasenotes"
  values:
    _comments:
        type: Marks the impact of this release


plugins:
- jekyll-sitemap
- jekyll-seo-tag
- jekyll-feed

exclude:
- Gemfile
- Gemfile.lock
- README.md
- LICENCE
